### ISSUE TITLE
Changes to directory/file structure required

### ISSUE THREAD

**Issue by QuestorX** [Cre-ator/UserProjectView#1]
The main file 'UserProjectView.php' of the MantisBT plugin must be located in the folder 'UserProjectView'.

Please create a directory/file structure like the following...

/ UserProjectView / pages / ...
/ UserProjectView / lang / ...
/ UserProjectView / core / ...
/ UserProjectView / UserProjectView.php
/ README.md
/ LICENSE
/ .gitignore
/ .gitattributes

**Comment by Cre-ator** [comment]
Thank you!
